version: '3'

services:
  db:
    container_name: polls-db
    image: mysql:5.6
    cap_add: 
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=polls
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - '33000:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    container_name: polls-web
    build:
      context: .
      dockerfile: dockerfiles/web 
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # links:
    #   - db

volumes:
  db:
    driver: local

