# Generated by Django 3.2.13 on 2022-09-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('backup_file', models.FileField(blank=True, default=None, null=True, upload_to='catalog_backups/l/%Y/%m/%d', verbose_name='Backup file')),
                ('biz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_backups', to='polls.choice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_catalog_backups', to='polls.question')),
            ],
            options={
                'db_table': 'atlas_catalogbackup',
            },
        ),
    ]
