# Generated by Django 3.2.13 on 2022-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_catalogbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogbackup',
            name='metric_details',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='Metric details'),
        ),
    ]
