# Generated by Django 3.2.13 on 2022-11-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_catalogbackup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogbackup',
            name='creator_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email of actual user incase if temp user creates backup'),
        ),
    ]
